### ISSUE TITLE
ChatPane.razor compile error in start solution

### ISSUE THREAD

**Issue by sk-bln** [AzureCosmosDB/cosmosdb-nosql-copilot#19]
ChatPane.razor line 309:
await chatService.ClearCacheAsync();
but the method is called
ChatService.CacheClearAsync,

**Comment by stvflowers** [comment]
ChatService.cs line 195 defines the method ClearCacheAsync()

**Comment by sandeepsnairms** [comment]
CacheClearAsync is a function in CosmosDbService,  ChatService has ClearCacheAsync. Please elaborate the issue.

**Comment by sk-bln** [comment]
It's fixed now, thanks
