### ISSUE TITLE
Resource Provider Registration: Microsoft.AlertsManagement

### ISSUE THREAD

**Issue by shribr** [AzureCosmosDB/cosmosdb-nosql-copilot#25]
Deployment script needs to register the **Microsoft.AlertsManagement** resource provider if it isn't already registered.

For reference, click [here](https://learn.microsoft.com/en-us/azure/azure-resource-manager/troubleshooting/error-register-resource-provider?tabs=azure-cli).

```
az provider show -n Microsoft.AlertsManagement --output table 
az provider register --namespace Microsoft.AlertsManagement

```

**Comment by markjbrown** [comment]
updated in predeploy
