### ISSUE TITLE
Cache search can leak information from other sessions.

### ISSUE THREAD

**Issue by qondoraudun** [AzureCosmosDB/cosmosdb-nosql-copilot#29]
As far as I can see, there is no consideration for partitions for the cache search. Each cached response could be grounded in and contain information supplied by the user in the original session. This could then be returned to a different session.

Session A
User: Hello, my name is James
Assistant: Hello James
U: What's my name?
A: Your name is James

Session B
U: Hello My name is Mark
A: Hello Mark
U: What's my name?
A: You name is James (Cached response)

**Comment by markjbrown** [comment]
@qondoraudun That scenario you describe would not happen. 

The cache operates over the context window. To get a cache hit, subsequent users have to follow the same set of prompts.

That said, the cache is shared across sessions. That is on purpose as cache values have limited use if they can only be used by the same user. 

If a per-user cache is what is desired, this is not difficult to implement. Just as with the chat history itself, the user name would need to be a part of the data model. In fact it would be the partition key, then used as a filter predicate with the vector query.

Thanks.
