### ISSUE TITLE
Python Version Needed

### ISSUE THREAD

**Issue by georgehu0815** [AzureCosmosDB/cosmosdb-nosql-copilot#64]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Sequoia? Sonoma? Ventura?)

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by markjbrown** [comment]
Thanks for the request. This repo is specifically intended as a .NET solution and a future version here which lives in the Aspire branch will be merged into main branch here shortly.

We will be producing an identical version of this one in Python at some point. In the mean time we have two Python samples here you can take a look at. https://github.com/microsoft/AzureDataRetrievalAugmentedGenerationSamples/tree/main/Python/CosmosDB-NoSQL_VectorSearch

We have some additional Python samples here and will be publishing new Python samples in our Gallery here as well. https://azurecosmosdb.github.io/gallery/?tags=generativeai&tags=python&tags=example

Thanks.
